[1.20] Update all Chinese translation (zh_cn) for Animals Dictionary
Alex-the-666/AlexsMobs pull request #1921
Opened 2024-01-02 11:30 UTC by NumberSir

2024-01-25 11:54 UTC, mc-kaishixiaxue requested changes

2024-01-25 11:54 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/bald_eagle.txt
> +    秃鹰是在树木丰富的山地群系中出
秃鹰→白头海雕

2024-01-25 12:57 UTC, mc-kaishixiaxue requested changes

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/bald_eagle.txt
> +    秃鹰是在树木丰富的山地群系中出
```suggestion
    白头海雕是在树木丰富的山地群系中出
```

请和 [zh_cn.json](https://github.com/AlexModGuy/AlexsMobs/blob/1.20/src/main/resources/assets/alexsmobs/lang/zh_cn.json) 相对应，其他文件需要检查。
Please correspond to zh_cn.json, other files need to be checked.

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/bald_eagle.txt
> +图返回。要停止控制秃鹰，只需下蹲即可。
```suggestion
图返回。要停止控制秃鹰，只需潜行即可。
```

`sneak` 要翻译为 `潜行`。
`sneak` is to be translated as `潜行`.

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/cachalot_whale.txt
> +    抹香鲸是一种庞大的、中性的哺乳
```suggestion
    抹香鲸是一种庞大的、中立的哺乳
```

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/cachalot_whale.txt
> +    奖励一般为麝香，是抹香鲸胃部分
```suggestion
    奖励一般为龙涎香，是抹香鲸胃部的分
```
`麝香`明显与抹香鲸无关，后面一句少了`的`变得不通顺。
`麝香` clearly has nothing to do with Cachalot Whale. The latter sentence becomes incoherent without `的`.

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/cachalot_whale.txt
> +一起合成，可以得到1个末地定位器，
```suggestion
一起合成，可以得到1个末影定位器，
```

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/cachalot_whale.txt
> +它可以在靠近要塞时显示末影传送门的
```suggestion
它可以在靠近要塞时显示末地传送门的
```

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/bald_eagle.txt
> +没的大型、中性的猛禽。它们经常前往附
```suggestion
没的大型、中立的猛禽。它们经常前往附
```

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/frilled_shark.txt
> +效果。
```suggestion
阻挡攻击时也会对攻击者施加“失血”效果。
```

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/leafcutter_ant.txt
> +    叶切蚁是一种小巧的昆虫，常常可
```suggestion
    切叶蚁是一种小巧的昆虫，常常可
```

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/mantis_shrimp.txt
> +食谱包括热带鱼、乌贼、守卫者和它们
```suggestion
食谱包括热带鱼、鱿鱼、守卫者和它们
```
原版鱿鱼？
Vanilla  squid?

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/mantis_shrimp.txt
> +、闲逛或破坏方块。
```suggestion
    可以命令驯服的螳螂虾跟随、坐下、
<NEWLINE>
游荡或破坏方块。
```
顿号不能写在行的开头。
The enumeration comma cannot be written at the beginning of a line.

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/mungus.txt
> +    可以喂食蘑菇君一个毒土豆来撤销
```suggestion
    可以喂食蘑菇君一个毒马铃薯来撤销
```

原版物品
Vanilla item

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/sea_bear.txt
> +    别戴宽边帽，像傻瓜那样。
```suggestion
    别像傻瓜那样戴阔边帽。
```

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/sea_bear.txt
> +那就用棍子在沙子上画一个反海熊圈。
```suggestion
那就用木棍在沙子上画一个反海熊圈。
```

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/tiger.txt
> +，能够从许多方块以外跃过来碾碎它的
```suggestion
    老虎是优秀的猎手，它们非常强壮，
<NEWLINE>
能够从许多方块以外跃过来碾碎它的
```

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/platypus.txt
> +，这使得它不得不依靠电力来捕猎和导
```suggestion
    鸭嘴兽的嗅觉、听觉和视力都很弱，
<NEWLINE>
这使得它不得不依靠电力来捕猎和导
```

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/platypus.txt
> +，可以用水桶运输鸭嘴兽。可以用龙虾
```suggestion
会大大增加。与其他小型水生生物一样，
<NEWLINE>
可以用水桶运输鸭嘴兽。可以用龙虾
```

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/platypus.txt
> +尾来繁殖鸭嘴兽，这是它最喜欢的食物
```suggestion
尾来繁殖鸭嘴兽，这是它最喜欢的食物。
```

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/bald_eagle.txt
> +，但它们也可以用于打猎。
```suggestion
样，被驯服的秃鹰可以停留、跟随或游荡，
<NEWLINE>
但它们也可以用于打猎。
```
逗号不能写在行的开头。
The comma cannot be written at the beginning of a line.

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/mungus.txt
> +发芽。
```suggestion
长出一棵蘑菇。喂食它更多相同的蘑菇
<NEWLINE>
就会有更多蘑菇在蘑菇君身上生根发芽。
```
量词不对。
This quantifier is wrong.

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/bald_eagle.txt
> +    要进行鹰猎，需要先制作猎鹰手套。
```suggestion
    要进行鹰猎，需要先合成猎鹰手套。
```
`craft` 要翻译为 `合成`。
`craft` is to be translated as `合成`.

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/bald_eagle.txt
> +    为了提高鹰猎技能，可以制作猎鹰兜帽。
```suggestion
    为了提高鹰猎技能，可以合成猎鹰兜帽。
```

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/cachalot_whale.txt
> +石，也可以用来制作回声定位器。还可
```suggestion
石，也可以用来合成回声定位器。还可
```

2024-01-25 12:57 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/mungus.txt
> +和炽足兽的亲戚，外表与他们相似。与
该文件都用`它们`，为什么这里用`他们`？
This file uses `它们`, so why do you use the word `他们` here?

2024-01-25 13:16 UTC, mc-kaishixiaxue requested changes
审查已完成。另外，以下几个在`zh_cn`文件夹中的文件还没有翻译，其对应的英文可能不一样：
The review has been completed. In addition, the following files in `zh_cn` folder have not been translated, and their English texts may not be the same:
1. cockroach.txt
2. crow.txt
3. elephant.txt
4. seal.txt

2024-01-29 18:08 UTC, NumberSir commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/bald_eagle.txt
> +图返回。要停止控制秃鹰，只需下蹲即可。
fixed in:
- bald_eagle

2024-01-29 18:10 UTC, NumberSir commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/cachalot_whale.txt
> +    抹香鲸是一种庞大的、中性的哺乳
fixed in:
- bald_eagle
- cachalot_whale
- frilled_shark

2024-01-29 18:13 UTC, NumberSir commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/cachalot_whale.txt
> +    奖励一般为麝香，是抹香鲸胃部分
fixed:
`麝香` -> `龙涎香`

2024-01-29 18:20 UTC, NumberSir commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/cachalot_whale.txt
> +一起合成，可以得到1个末地定位器，
fixed

2024-01-29 18:20 UTC, NumberSir commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/cachalot_whale.txt
> +它可以在靠近要塞时显示末影传送门的
fixed

2024-01-29 18:26 UTC, NumberSir commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/mungus.txt
> +    可以喂食蘑菇君一个毒土豆来撤销
fixed

2024-01-29 18:29 UTC, NumberSir commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/mungus.txt
> +和炽足兽的亲戚，外表与他们相似。与
fixed

2024-01-29 18:42 UTC, NumberSir commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/bald_eagle.txt
> +    秃鹰是在树木丰富的山地群系中出
fixed in:
- bald_eagle
- cachalot_whale
- leafcutter_ant

2024-01-29 18:55 UTC, NumberSir commented
> 审查已完成。另外，以下几个在`zh_cn`文件夹中的文件还没有翻译，其对应的英文可能不一样： The review has been completed. In addition, the following files in `zh_cn` folder have not been translated, and their English texts may be different:
> 
> 1. cockroach.txt
> 2. crow.txt
> 3. elephant.txt
> 4. seal.txt

感谢审查，提到的问题已修复。质量过低的译文已改用我在 1.19.3 版本分支提交过的翻译版本：#1600

2024-02-02 12:35 UTC, mc-kaishixiaxue requested changes

2024-02-02 12:35 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/cockroach.txt
> +他们会躲避阳光。这种虫子避光，以免
代词错误，该文件出现了3个`他们`。
Wrong pronoun, this file appears 3 `他们`.

2024-02-02 12:35 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/crow.txt
> +    下蹲时可以让肩膀上的乌鸦下来。
```suggestion
    潜行可以让肩膀上的乌鸦下来。
```

2024-02-02 12:35 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/seal.txt
> +鱼去喂他可以引发你和海豹之间的原始
```suggestion
    当海豹在陆地上晒太阳时，喂给它
<NEWLINE>
3 条鱼可以发起你和海豹之间的原始
```

2024-02-02 12:35 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/frilled_shark.txt
> +反光的牙齿吸引本能向光的乌贼来捕猎
`乌贼`是原版的`鱿鱼`还是本模组的`大王乌贼`？
Is `乌贼` vanilla `Squid` or this mod's `Giant Squid`?

2024-02-02 12:35 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/mungus.txt
> +时背上有 5 个蘑菇，蘑菇君将发出剧
`蘑菇`请统一量词。
`蘑菇` Please standardize the quantifier.

2024-02-02 12:35 UTC, mc-kaishixiaxue commented on src/main/resources/assets/alexsmobs/book/animal_dictionary/zh_cn/seal.txt
> +品比如鲨鱼利齿、锥形鳞甲或鹦鹉螺壳。
```suggestion
或沙子，但有时也可能是比较罕见的物
<NEWLINE>
品，比如鲨鱼利齿、锥形鳞甲或鹦鹉螺壳。
```

2024-03-05 17:36 UTC, merged